defaults:
    - /hydra/callbacks:
        - log_job_return_callback
    - override hydra/launcher: submitit_slurm
    - _self_

data:
    data_dir: data
    logs_dir: logs
    batch_size: 64
    num_workers: 4
    latent_dim: 3

train:
    accelerator: gpu
    epochs: 5

optim:
    lr: 0.001
