RUN := uv run python
SRC := {{ project_name }}

define PRINT_HELP_PYSCRIPT
import re, sys

BOLD = '\033[1m'
BLUE = '\033[94m'
END = '\033[0m'

print("Usage: make <target>\n")
print(BOLD + "%-20s%s" % ("target", "description") + END)
for line in sys.stdin:
	match = re.match(r'^([a-zA-Z_-]+):.*?## (.*)$$', line)
	if match:
		target, help = match.groups()
		print( BLUE + "%-20s" % (target) + END + "%s" % (help))
endef
export PRINT_HELP_PYSCRIPT

help: ## Show this help.
	@$(RUN) python -c "$$PRINT_HELP_PYSCRIPT" < $(MAKEFILE_LIST)

train: ## Train the model using slurm.
	sbatch slurm/train.sh

.PHONY: help, train
